name: nuisanceiv-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - ipykernel
  - numpy
  - pandas
  - networkx
  - matplotlib
  - scipy
  - statsmodels
  - seaborn
  - linearmodels
  - openssl
  - pickle
  - pip:
    - warnings